f1=open("secfile.txt","w")
f1.write("This is my first file in python.\nwant to work with files \n This is my third line")
f1.close()
f1=open("secfile.txt","r")
print("name of file",f1.name)
print("close of file",f1.close)
print("mode of file",f1.mode)
print(f1.read())
print("---------")
f1.seek(0,0)
ff=f1.readlines()
print(ff)
print("no of lines:",len(ff))
